const labels = {
  'Artist': {
    name: 'Artist',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Loan/Out': {
    name: 'Loan/Out',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Role': {
    name: 'Role',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Project Name': {
    name: 'Project Name',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Company': {
    name: 'Company',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Compensation': {
    name: 'Compensation',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Contingency': {
    name: 'Contingency',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Guarantee': {
    name: 'Guarantee',
    id: '',
    type: 'longtext',
    placeholder: '',
  },
  'Dates': {
    name: 'Dates',
    id: '',
    type: 'date',
    placeholder: '',
  },
  'Location': {
    name: 'Location',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Payment': {
    name: 'Payment',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Wire Information': {
    name: 'Wire Information',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Work Days': {
    name: 'Work Days',
    id: '',
    type: 'number',
    placeholder: '',
  },
  'Post Production Days': {
    name: 'Post Production Days',
    id: '',
    type: 'number',
    placeholder: '',
  },
  'Transportation': {
    name: 'Transportation',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Dressing Room': {
    name: 'Dressing Room',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Directors Meeting': {
    name: 'Directors Meeting',
    id: '',
    type: 'longtext',
    placeholder: '',
  },
  'Per Diem': {
    name: 'Per Diem',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Billing Block': {
    name: 'Billing Block',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Approvals': {
    name: 'Approvals',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Merchandising': {
    name: 'Merchandising',
    id: '',
    type: 'longtext',
    placeholder: '',
  },
  'Union': {
    name: 'Union',
    id: '',
    type: 'longtext',
    placeholder: '',
  },
  'F&O': {
    name: 'F&O',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Idemnities': {
    name: 'Idemnities',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Special Provisions': {
    name: 'Special Provisions',
    id: '',
    type: 'longtext',
    placeholder: '',
  },
  'Makeup, Hair, & Wardrobe': {
    name: 'Makeup, Hair, & Wardrobe',
    id: 'MHWardrobe',
    type: 'text',
    placeholder: '',
  },
  'Security Guard': {
    name: 'Security Guard',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Personal Assistant': {
    name: 'Personal Assistant',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'Premiere Tickets': {
    name: 'Premiere Tickets',
    id: '',
    type: 'text',
    placeholder: '',
  },
  'DVD / Blue-Ray Cop': {
    name: 'DVD / Blue-Ray Cop',
    id: '',
    type: 'text',
    placeholder: '',
  },
};
export default labels;
