const initialState = {
    artistName: '',
    projectName: '',
    loanOut: '',
    startDate: [Date],
    role: '',
    company: '',
    compensation: 0,
    contigency: '',
    guarantee: '',
    dates: [Date],
    location: '',
    payment: '',
    wireInformation: '',
    workDay: 0,
    postProdDays: 0,
    transportation: '',
    dressingRoom: '',
    directorsMeeting: '',
    perDiem: 0,
    billingBlock: '',
    approvals: 0,
    merchandising: '',
    union: '',
    fo: '',
    idemnities: '',
    provisions: '',
    MHWardrobe: '',
    security: '',
    assistant: 0,
    premiereTickets: 0,
    physicalCopy: '',
    signed: false,
}

export default initialState;